<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="73380" started-at="2021-11-25T13:46:25 GMT+04:00" finished-at="2021-11-25T13:47:39 GMT+04:00">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="73380" started-at="2021-11-25T13:46:25 GMT+04:00" finished-at="2021-11-25T13:47:39 GMT+04:00">
      <class name="dockerizedSelenium.AzureSeleniumTest">
        <test-method status="PASS" signature="tearUp()[pri:0, instance:dockerizedSelenium.AzureSeleniumTest@5702b3b1]" name="tearUp" is-config="true" duration-ms="60299" started-at="2021-11-25T13:46:25 GMT+04:00" finished-at="2021-11-25T13:47:26 GMT+04:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearUp -->
        <test-method status="PASS" signature="eVisaTrackApplication()[pri:1, instance:dockerizedSelenium.AzureSeleniumTest@5702b3b1]" name="eVisaTrackApplication" duration-ms="4851" started-at="2021-11-25T13:47:26 GMT+04:00" finished-at="2021-11-25T13:47:31 GMT+04:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- eVisaTrackApplication -->
        <test-method status="PASS" signature="contactUsText()[pri:2, instance:dockerizedSelenium.AzureSeleniumTest@5702b3b1]" name="contactUsText" duration-ms="2941" started-at="2021-11-25T13:47:31 GMT+04:00" finished-at="2021-11-25T13:47:34 GMT+04:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactUsText -->
        <test-method status="FAIL" signature="captchaCheck()[pri:3, instance:dockerizedSelenium.AzureSeleniumTest@5702b3b1]" name="captchaCheck" duration-ms="3588" started-at="2021-11-25T13:47:34 GMT+04:00" finished-at="2021-11-25T13:47:37 GMT+04:00">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at dockerizedSelenium.AzureSeleniumTest.captchaCheck(AzureSeleniumTest.java:75)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captchaCheck -->
        <test-method status="PASS" signature="titleCheck()[pri:4, instance:dockerizedSelenium.AzureSeleniumTest@5702b3b1]" name="titleCheck" duration-ms="12" started-at="2021-11-25T13:47:38 GMT+04:00" finished-at="2021-11-25T13:47:38 GMT+04:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleCheck -->
        <test-method status="PASS" signature="teraDown()[pri:0, instance:dockerizedSelenium.AzureSeleniumTest@5702b3b1]" name="teraDown" is-config="true" duration-ms="1267" started-at="2021-11-25T13:47:38 GMT+04:00" finished-at="2021-11-25T13:47:39 GMT+04:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teraDown -->
      </class> <!-- dockerizedSelenium.AzureSeleniumTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
